### ISSUE TITLE
Array notation seems to be incorrectly implemented

### ISSUE THREAD

**Issue by vonas** [webextensions/copy-files-from-to#14]
I installed the package like this:
```
$ npm install copy-files-from-to --save-dev
```

Then I added the `copyFiles` entry to my `package.json` as described in the README:
```json
// ...
"copyFiles": [
  {
    "from": [
      "node_modules/mermaid/dist/mermaid.min.js"
    ],
    "to": "mermaid/assets/"
  }
]
```

And finally I executed `$ npx copy-files-from-to` to get this output:
```
Reading copy instructions from file package.json
C:\Users\Jonas\package\node_modules\glob-parent\index.js:23
    str = str.replace(backslash, slash);
              ^

TypeError: str.replace is not a function
    at globParent (C:\Users\Jonas\package\node_modules\←[4mglob-parent←[24m\index.js:23:15)
    at C:\Users\Jonas\package\node_modules\←[4mcopy-files-from-to←[24m\index.js:593:41
    at Array.forEach (<anonymous>)
    at C:\Users\Jonas\package\node_modules\←[4mcopy-files-from-to←[24m\index.js:585:33
    at Array.forEach (<anonymous>)
    at C:\Users\Jonas\package\node_modules\←[4mcopy-files-from-to←[24m\index.js:570:23
    at Object.<anonymous> (C:\Users\Jonas\package\node_modules\←[4mcopy-files-from-to←[24m\index.js:617:10)
←[90m    at Module._compile (internal/modules/cjs/loader.js:959:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:815:32)←[39m
```

I inserted a `console.debug(str)` at the right place in `node_modules\glob-parent\index.js` which told me that `str` is equal to `[ 'node_modules/mermaid/dist/mermaid.min.js' ]`. That's probably not intended.

**Comment by webextensions** [comment]
@vonas 
Please try again with 2.3.0 onwards :-)

Also, note that the documentation has been slightly updated to say that array notation for "from" should be used for glob expressions. Your given example should work fine now on Windows machines.
