### ISSUE TITLE
Error: resourcePath.indexOf is not a function

### ISSUE THREAD

**Issue by aliskhanoff** [webextensions/copy-files-from-to#17]
type: 
- [ *] error
Environment:

- Node: 14.16.1 
- Yarn: v1.22.5
- NPM: 6.14.12

**copy-files-from-to.json** configuration

`{
    "copyFiles": [        
        {
            "from": ["./backend/**/*", "!./backend/./node_modules"],
            "to": "./pre-release"
        },
        
        {
            "from": "./frontend/build/**/*",
            "to": "./pre-release/public"
        },

        {
            "from": ["./files/.pre-release/**/*", "!./files/.pre-release/database.js"],
            "to": "./pre-release"
        },

        {
            "from": ["./files/.pre-release/database.js"],
            "to": "./pre-release/config"
        }
        
    ]
}`

✓ Already exists pre-release/public/static/js/runtime-main.1c3f5376.js.map
E:\Werken\werkmarkt\node_modules\copy-files-from-to\utils.js:39
            resourcePath.indexOf('https://') === 0 ||
                         ^

TypeError: resourcePath.indexOf is not a function
    at Object.isRemoteResource (E:\Werken\werkmarkt\node_modules\copy-files-from-to\utils.js:39:26)
    at Object.getRelativePath (E:\Werken\werkmarkt\node_modules\copy-files-from-to\utils.js:48:19)
    at doCopyFile (E:\Werken\werkmarkt\node_modules\copy-files-from-to\main.js:499:52)
    at E:\Werken\werkmarkt\node_modules\copy-files-from-to\main.js:622:25
    at E:\Werken\werkmarkt\node_modules\copy-files-from-to\node_modules\async\dist\async.js:2554:44
    at replenish (E:\Werken\werkmarkt\node_modules\copy-files-from-to\node_modules\async\dist\async.js:443:21)
    at E:\Werken\werkmarkt\node_modules\copy-files-from-to\node_modules\async\dist\async.js:448:13
    at Object.eachLimit$1 (E:\Werken\werkmarkt\node_modules\copy-files-from-to\node_modules\async\dist\async.js:2684:34)
    at Object.awaitable (E:\Werken\werkmarkt\node_modules\copy-files-from-to\node_modules\async\dist\async.js:211:32)  
    at main (E:\Werken\werkmarkt\node_modules\copy-files-from-to\main.js:615:19)
error Command failed with exit code 1.

Hello there! Am trying copy all files from **backend** and **frontend** folder to pre-release, and i faced with this kind of error, and i don't know how to figure out from this point. Thanks.

**Comment by webextensions** [comment]
@aliskhanoff 
Apparently, when there were no entries matching those patterns, this error could come up.

The error has been fixed with https://github.com/webextensions/copy-files-from-to/commit/95226cb259af818aa277bb3e975628d7bf8a21f2

Please upgrade to v3.2.1 and it should work fine.
